export const env = {
  NEXTAUTH_URL: process.env.NEXTAUTH_URL,
  // APPLICATION API URL
  API_URL: process.env.API_URL,
  // COOKIES
  COOKIE_SIGNING_SECRET: process.env.COOKIE_SIGNING_SECRET,
  // GOOGLE
  GOOGLE_OAUTH_CLIENT_ID: process.env.GOOGLE_OAUTH_CLIENT_ID,
  GOOGLE_OAUTH_CLIENT_SECRET: process.env.GOOGLE_OAUTH_CLIENT_SECRET,
  // JWT
  JWT_SIGNING_KEY: process.env.JWT_SIGNING_KEY,
  // SUPPORT EMAIL
  SUPPORT_EMAIL: process.env.SUPPORT_EMAIL,
  // the application title in browser tab
  TITLE_BAR_BASE: process.env.TITLE_BAR_BASE,
};
