export const env = {
  NEXTAUTH_URL: process.env.NEXTAUTH_URL,
  COOKIE_SIGNING_SECRET: process.env.COOKIE_SIGNING_SECRET,
  GOOGLE_OAUTH_CLIENT_ID: process.env.GOOGLE_OAUTH_CLIENT_ID,
  GOOGLE_OAUTH_CLIENT_SECRET: process.env.GOOGLE_OAUTH_CLIENT_SECRET,
};
