import { registerAs } from '@nestjs/config'

export default registerAs('stripe', () => ({
    STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
    STRIPE_SUBSCRIPTION_PRODUCT_ID: process.env.STRIPE_SUBSCRIPTION_PRODUCT_ID,
    STRIPE_SUBSCRIPTION_MONTHLY_PRICE_ID: process.env.STRIPE_SUBSCRIPTION_MONTHLY_PRICE_ID,
    STRIPE_SUBSCRIPTION_ANNUAL_PRICE_ID: process.env.STRIPE_SUBSCRIPTION_ANNUAL_PRICE_ID,
    STRIPE_BILLING_PORTAL_REDIRECT_URL: process.env.STRIPE_BILLING_PORTAL_REDIRECT_URL,
    STRIPE_CHECKOUT_SUCCESS_REDIRECT_URL: process.env.STRIPE_CHECKOUT_SUCCESS_REDIRECT_URL,
    STRIPE_CHECKOUT_CANCEL_REDIRECT_URL: process.env.STRIPE_CHECKOUT_CANCEL_REDIRECT_URL,
  }))
  