import { join } from 'path';
import { Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';

@Injectable()
export class GlobalConfigService {
  constructor(private configService: ConfigService) {}

  private frontendURL = this.configService.get('common.FRONTEND_URL');

  get port() {
    return this.configService.get('common.PORT') || 5000;
  }

  get inDevelopment() {
    return (
      this.configService.get('common.NODE_ENV').toLowerCase() === 'development'
    );
  }

  get releaseVersion(): string {
    return process.env.npm_package_version;
  }

  get environmentName(): ApplicationEnvironment {
    return this.inDevelopment ? 'development' : 'production';
  }

  get autoGeneratedGraphQLSchemaFile() {
    return join(process.cwd(), 'schema.graphql');
  }

  // Cors config BOTH for Apollo Server & Express
  get corsConfig() {
    return {
      // origin: '*',
      origin: 'http://' + this.frontendURL,
      credentials: true,
    };
  }
}

type ApplicationEnvironment = 'development' | 'production';
