version: '2'

services:
  postgres:
    container_name: 'postgres'
    image: 'postgres:latest'
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data/'
    environment:
        POSTGRES_PASSWORD: devpassword
  redis:
    container_name: 'redis'
    image: 'redis:latest'
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - 'redisdata:/data'

volumes:
  pgdata:
  redisdata: