import { Module } from '@nestjs/common';
import { StripeModule } from 'nestjs-stripe';
import { GraphQLModule } from '@nestjs/graphql';
import { SentryModule } from '@ntegral/nestjs-sentry';
//
import { ImageUploadModule } from '@monorepo-starter/api-upload';
//
import { UserModule } from './user/user.module';
import { AuthModule } from './auth/auth.module';
import { PrismaModule } from './prisma/prisma.module';
import { AccountModule } from './account/account.module';
import { LocalConfigModule } from './config/config.module';
import { GlobalConfigService } from './config/services/global.config';
import { StripeConfigService } from './config/services/stripe.config';
import { SentryConfigService } from './config/services/sentry.config';
import { SubscriptionModule } from './subscription/subscription.module';
import { CurrencyScalar } from './common/graphql/currency-scalar';

@Module({
  imports: [
    AccountModule,
    AuthModule,
    UserModule,
    PrismaModule,
    AccountModule,
    ImageUploadModule,
    LocalConfigModule,
    SubscriptionModule,
    SentryModule.forRootAsync({
      imports: [LocalConfigModule],
      useFactory: async (
        config: SentryConfigService,
        { environmentName, releaseVersion }: GlobalConfigService
      ) => ({
        dsn: config.dsn,
        debug: config.debug,
        logLevel: config.logLevel,
        environment: environmentName,
        release: releaseVersion, // must create a release in sentry.io dashboard
      }),
      inject: [SentryConfigService, GlobalConfigService],
    }),
    GraphQLModule.forRootAsync({
      imports: [LocalConfigModule],
      useFactory: (localConfigService: GlobalConfigService) => ({
        cors: localConfigService.corsConfig,
        autoSchemaFile: localConfigService.autoGeneratedGraphQLSchemaFile,
      }),
      inject: [GlobalConfigService],
    }),
    StripeModule.forRootAsync({
      imports: [LocalConfigModule],
      useFactory: (localConfigService: StripeConfigService) => ({
        apiKey: localConfigService.stripeSecretKey,
        apiVersion: localConfigService.stripeApiVersion,
      }),
      inject: [StripeConfigService],
    }),
  ],
})
export class AppModule {}
