import { Module } from '@nestjs/common';
import { GraphQLModule } from '@nestjs/graphql';
import { StripeModule } from 'nestjs-stripe';

import { CaslModule } from './casl/casl.module';
import { UserModule } from './user/user.module';
import { AuthModule } from './auth/auth.module';
import { PrismaModule } from './prisma/prisma.module';
import { AccountModule } from './account/account.module';
import { LocalConfigModule } from './config/config.module';
import { CustomLoggerModule } from './common/logger/log.module';
import { GlobalConfigService } from './config/services/global.config';
import { StripeConfigService } from './config/services/stripe.config';
import { SubscriptionModule } from './subscription/subscription.module';

@Module({
  imports: [
    AccountModule,
    AuthModule,
    CaslModule,
    UserModule,
    PrismaModule,
    AccountModule,
    LocalConfigModule,
    SubscriptionModule,
    CustomLoggerModule,
    GraphQLModule.forRootAsync({
      imports: [LocalConfigModule],
      useFactory: (localConfigService: GlobalConfigService) => ({
        autoSchemaFile: localConfigService.autoGeneratedGraphQLSchemaFile,
        cors: localConfigService.corsConfig,
      }),
      inject: [GlobalConfigService],
    }),
    StripeModule.forRootAsync({
      imports: [LocalConfigModule],
      useFactory: (localConfigService: StripeConfigService) => ({
        apiKey: localConfigService.stripeSecretKey,
        apiVersion: localConfigService.stripeApiVersion,
      }),
      inject: [StripeConfigService],
    }),
  ],
})
export class AppModule {}
